### ISSUE TITLE
FYI: Github location of Kopano OL Extension

### ISSUE THREAD

**Issue by fbartels** [snorre-k/KOE#1]
Hi @snorre-k ,

I just found your repo on Github and just wanted to drop by and say that there is also an official mirror of the project on Github. You can find it at https://github.com/Kopano-mirror/kopano-ol-extension.

If you are interested in pushing your changes upstream or have any further question let me know.

Regards

**Comment by snorre-k** [comment]
Hi @fbartels ,

I only added a VS 2017 setup project to KOL to be able to build an installable msi.
The standard 'one click setup' output is installed for a single user only.

No other parts of the project have been changed :)

If you want, I will push this additional VS project and the readme for compilation upstream.

BR
Snorre
